# Generated by Django 5.0.6 on 2024-05-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='book-covers/%y/%m/%d')),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, default='Uncategorized', max_length=100, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
