# Generated by Django 5.0.6 on 2024-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBooks', '0002_remove_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='book-covers/24/05/14/frankenstein.jpeg', upload_to='book-covers/%y/%m/%d'),
        ),
    ]
