# Generated by Django 5.0.6 on 2024-05-21 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('manageBooks', '0005_book_language_book_no_of_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Science fiction', 'Science fiction'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Autobiographical', 'Autobiographical'), ('Fantasy', 'Fantasy'), ('Drama', 'Drama'), ('History', 'History'), ('Science', 'Science')], default='Any', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic'), ('Spanish', 'Spanish'), ('French', 'French')], default='English', max_length=20),
        ),
        migrations.CreateModel(
            name='Borrowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageBooks.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
