# Generated by Django 5.0.6 on 2024-05-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBooks', '0007_alter_borrowed_options_rename_user_borrowed_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='current_borrower',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isAvailable',
        ),
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.IntegerField(default=0),
        ),
    ]
