# Generated by Django 5.0.6 on 2024-05-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBooks', '0010_rename_profile_borrowed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed_copies',
            field=models.IntegerField(default=0),
        ),
    ]
