# Generated by Django 4.2.13 on 2024-05-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBooks', '0013_book_ratings_book_reviews_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
